dataset:
  root_dir: VOCdevkit/VOC2012
  name_list_dir: datasets/voc
  num_classes: 21
  crop_size: 320
  resize_range: [512, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

work_dir:
  dir: work_dir_voc
  ckpt_dir: checkpoints
  pred_dir: predictions
  segs_dir: segs
  tb_logger_dir: tb_logger

train:
  split: train_aug
  samples_per_gpu: 4 #4 #2
  max_iters: 100000
  cam_iters: 2000
  eval_iters: 2000
  log_iters: 10


val:
  split: train

optimizer:
  type: AdamW
  learning_rate: 2e-4 #2e-4
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 50 #1500
  warmup_ratio: 1e-6
  power: 1.0

clip_init:
  clip_pretrain_path: pretrained/ViT-B-16.pt
  embedding_dim: 256
  in_channels: [768, 768,768,768]

VMMODEL:
  MODEL:
    TYPE: vssm
    NAME: vssm1_tiny_0230s
    DROP_PATH_RATE: 0.2
    VSSM:
      EMBED_DIM: 96
      DEPTHS: [ 2, 2, 8, 2 ]
      SSM_D_STATE: 1
      SSM_DT_RANK: "auto"
      SSM_RATIO: 1.0
      SSM_CONV: 3
      SSM_CONV_BIAS: false
      SSM_FORWARDTYPE: "v05_noz" # v3_noz
      MLP_RATIO: 4.0
      DOWNSAMPLE: "v3"
      PATCHEMBED: "v2"
      NORM_LAYER: "ln2d"

      